### ISSUE TITLE
关于 MiniExtend Fork

### ISSUE THREAD

**Issue by 0-0000** [kaikaibenkai/MiniExtendDoc#3]
我发现本应存在的 `kaikaibenkai/MiniExtend fork` 在 Insights 意外不见了，这意味着除非手动链接，这两个仓库无法连接，而且在 *README* 中也没有正确指向原 MiniExtend 仓库。

---
- [x] 修改仓库名称
- [x] 修改`./README.md`中的源代码仓库链接

**Comment by 0-0000** [comment]
你应该将你原有的 fork 重命名为 MiniExtend 而不是重新创建新的，这样在 github 上无法确定仓库之间的关系。  
你可以只 fork `develop` 分支，然后新建 `docs` 分支并在其中管理文档。

**Comment by kaikaibenkai** [comment]
fork是用于贡献代码、处理pr的，而文档被分离出来后已经无需存放源代码，也不需要合并到原仓库，故无需使用fork功能

**Comment by 0-0000** [comment]
所以你决定只写文档了？

**Comment by kaikaibenkai** [comment]
我将在`./README.md`中放置原仓库的链接

**Comment by kaikaibenkai** [comment]
毕竟Vuepress也不是从Vue3源代码仓库中fork出来的，对吧

**Comment by kaikaibenkai** [comment]
> 所以你决定只写文档了？

如果没有空余时间的话

**Comment by 0-0000** [comment]
> 毕竟Vuepress也不是从Vue3源代码仓库中fork出来的，对吧

但是 Vuepress 不是 Vue3 ，它是 Vue3 的一个衍生产品，但你的仓库目前只被作为 MiniExtend 的文档，不算做 MiniExtend ，但你将 `MiniExtned` 作为仓库名。

**Comment by kaikaibenkai** [comment]
如何使此仓库名为`MiniExtendDocs`而Page部署在`kaikaibenkai.github.io/MiniExtend`呢？
我在找解决方案

**Comment by 0-0000** [comment]
不必部署在 `/MiniExtend` 下，我会修改链接

**Comment by kaikaibenkai** [comment]
@0-0000 已部署到`kaikaibenkai.github.io/MiniExtendDoc`
