### ISSUE TITLE
同步 MiniExtend 3

### ISSUE THREAD

**Issue by 0-0000** [kaikaibenkai/MiniExtendDoc#6]
# 同步 MiniExtend 3
在 MiniExtendDoc 同步 MiniExtend 2 前， MiniExtend 3 已发布，目前的最新版本为 3.0.2 ，需同步 MiniExtend 3.0 。  
- [x] Copyright © 2022 kaikaibenkai -> Copyright © 2022-2023 kaikaibenkai  
- [x] 完善侧边链接，顺序如下:  
1. 简介: 基于 *README.md*    
2. 约定: 基于 *docs/document.md*   
3. 搭建环境: 基于 *docs/environment.md*  
4. Core: 基于 *docs/core.md*  
5. Log: 基于 *docs/log.md*  
6. Time: 基于 *docs/time.md*  
7. Object: 基于 *docs/object.md*  
8. Event: 基于 *docs/event.md*  
9. UI: 基于 *docs/ui.md*  
10. MiniExtend 更新日志: 基于 *CHANGELOG.md*  
链接内容可适当发挥。  
- [x] 简介、约定与搭建环境  
- [x] Core  
- [x] Log  
- [x] Time  
- [x] Object  
- [x] Event  
- [x] UI  
- [x] MiniExtend 更新日志  
- [x] 其它扩展  
- [ ] 搭建 Github Page 环境

**Comment by 0-0000** [comment]
## 优化文档的建议
1. 使用分割线，文档内容较长，应通过分割线来将描述同一部分的内容的部分集中在一起，目前观测文档很少使用分割线。

**Comment by kaikaibenkai** [comment]
由于 Vuepress 默认主题的标题下有分割线，就不再另加分割线了
